# -*- mode: yaml
#
# Exawind Python Library's Conda environment definition file
#
# Usage:
#  conda env create -f etc/environment.yml

name: exawind

dependencies:
  - python=3
  - pip
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - ruamel_yaml
  - ipython
  - pytz
